NAA/Controllers/ApplicantAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using NAA.Services.Service;
using NAA.Services.IServices;
using NAA.Data;

namespace NAA.Controllers
{
    [Authorize(Roles = Helpers.Constants.Roles.Applicant)]
    public class ApplicantAdminController : Controller
    {
        private IApplicantService _applicantService;

        public ApplicantAdminController()
        {
            _applicantService = new ApplicantService();
        }



        [Authorize(Roles = Helpers.Constants.Roles.Admin)]
        public ActionResult Index()
        {
            return View(_applicantService.GetApplicants());
        }

        //getting data for edit left at this point
        [HttpGet]
        public ActionResult EditApplicant ()
        {
            var userId = HttpContext.User.Identity.GetUserId();
            var applicant = _applicantService.GetApplicant(userId);
            return View(applicant);
        }

        //posting method once data has been collected via the get method for edit

        [HttpPost]
        public ActionResult EditApplicant(Applicant applicant)
        {
            try
            {
                _applicantService.EditApplicant(applicant);
                return RedirectToAction("Applicant","Applicant");
            }
            catch (Exception ex)
            {
                return View(applicant);
            }
        }

        //get action before creating
        [HttpGet]
        public ActionResult AddApplicant(string applicant)
        {
            return View();
        }
        //Add action for adding an applicant to the database
        [HttpPost]

        public ActionResult AddApplicant(Applicant applicant)
        {
            _applicantService.AddApplicant(applicant);
            return RedirectToAction("Applicant", "Applicant");
        }

    }
}

NAA/Controllers/ApplicationController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.ServiceModel.Configuration;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using NAA.Data;
using NAA.Helpers;
using NAA.Models;
using NAA.Services.IServices;
using NAA.Services.Service;
using NAA.SheffieldUniCourses;
using NAA.SHUWebService;

namespace NAA.Controllers
{

    /// Interface to handle UI operations
    [Authorize(Roles = Helpers.Constants.Roles.Applicant)]
    public class ApplicationController : Controller
    {
        private IApplicationService _applicationService;
        private IUniversityService _universityService;
        private IApplicantService _applicantService;
        private readonly UniversityHelper _universityHelper;

        /// Constructor to initlize class object

        public ApplicationController()
        {
            _applicationService = new ApplicationService();
            _universityService = new UniversityService();
            _applicantService = new ApplicantService();
            _universityHelper = new UniversityHelper();
        }

        public UniversityHelper UniversityHelper
        {
            get { return _universityHelper; }
        }


        /// Action for listing application for applicant
        /// <returns>Index view that contains listing of applications</returns>
        public ActionResult Index()
        {
            var userId = HttpContext.User.Identity.GetUserId();

            var applicant = _applicantService.GetApplicant(userId);
            var model = new ApplicationListViewModel();

            if (applicant != null)
            {
                int applicantId = applicant.ApplicantId;
                model.Applications = _applicationService.GetApplicationsByApplicant(applicantId);
                model.ApplicantId = applicantId;
            }

            return View("Index", model);
        }

     
        /// Action to load application in add mode for new application or in edit mode for edit
        /// <param name="applicantId">Applicant id to which application belongs</param>
        /// <param name="applicationId">Application id to edit or null for new application</param>
        /// <returns>Edit page</returns>
        [HttpGet]
        public ActionResult Edit(int applicantId, int? applicationId)
        {
            ApplicationViewModel model = GetApplicationModel(applicantId, applicationId);
            
            return View("EditApplication", model);
        }

        /// Action to load application in add mode for new application or in edit mode for edit
        /// <param name="applicantId">Applicant id to which application belongs</param>
        /// <param name="applicationId">Application id to edit or null for new application</param>
        /// <returns>Edit page</returns>
        [HttpGet]
        public ActionResult DisplayApplication(int applicantId, int? applicationId)
        {
            ApplicationViewModel model = GetApplicationModel(applicantId, applicationId);
           
            return View("DisplayApplication", model);
        }


        private ApplicationViewModel GetApplicationModel(int applicantId, int? applicationId)
        {
           var model = new ApplicationViewModel();
            
            if (!applicationId.HasValue)
            {
                model.ApplicantId = applicantId;
                model.ApplicantName = _applicantService.GetApplicant(applicantId).ApplicantName;
            }
            else
            {
                var application = _applicationService.GetApplication(applicationId.Value);

                if (application == null)
                {
                    return model;
                }

                model.ApplicationId = application.ApplicantId;
                model.CourseName = application.CourseName.Trim();
                model.PersonalStatement = application.PersonalStatement;
                model.TeacherReference = application.TeacherReference;
                model.TeacherContactDetails = application.TeacherContactDetails.Trim();
                model.UniversityId = application.UniversityId;
                model.UniversityOffer = application.UniversityOffer;
                model.Firm = application.Firm;
                model.ApplicantId = application.ApplicantId;
                model.ApplicantName = application.Applicant.ApplicantName.Trim();
                model.OfferCondition = application.OfferCondition;
                model.RejectReason = application.RejectReason;

                var university = _universityHelper.GetUniversity(model.UniversityId);

                if (university != null)
                {
                    model.UniversityName = university.UniversityName.Trim();
                }
            }

            model = SetApplicationViewModel(model);

            var courses = _universityHelper.GetCourses(model.UniversityId);

            if (courses.Any(x => x.CourseName == model.CourseName))
            {
                var course = courses.First(x => x.CourseName == model.CourseName);

                model.CourseContent = course.CourseContent.Trim();
                model.CourseDescription = course.CourseDescription.Trim();
                model.EntryCriteria = course.EntryCriteria.Trim();
            }

            return model;
        }


        /// Method to set field for drop-down list
        /// <param name="model"></param>
        /// <returns></returns>
        private ApplicationViewModel SetApplicationViewModel(ApplicationViewModel model)
        {
            var universities = _universityService.GetUniversities();
            model.Universities = universities
                .Select(s => new SelectListItem
                {
                    Value = s.UniversityId.ToString(),
                    Text = s.UniversityName.Trim()
                }).ToList();

            if (model.UniversityId > 0)
            {
                model.Courses = UniversityHelper.GetCourses(model.UniversityId).Select(s => new SelectListItem
                {
                    Value = s.CourseName,
                    Text = s.CourseName.Trim()
                }).ToList();
            }
            else
            {
                model.Courses = UniversityHelper.GetCourses(universities.First().UniversityId).Select(s => new SelectListItem
                {
                    Value = s.CourseName,
                    Text = s.CourseName.Trim()
                }).ToList();
            }

            return model;
        }


        /// Action to save application
        /// <param name="model"></param>
        /// <returns>Redirect to applications list page or stay on same page if any errors occur </returns>
        [HttpPost]
        public ActionResult Edit(ApplicationViewModel model)
        {
            try
            {
                model = SetApplicationViewModel(model);

                if (ModelState.IsValid)
                {
                    var application = new Application
                    {
                        ApplicationId = model.ApplicationId,
                        CourseName = model.CourseName,
                        PersonalStatement = model.PersonalStatement,
                        TeacherReference = model.TeacherReference,
                        TeacherContactDetails = model.TeacherContactDetails,
                        UniversityId = model.UniversityId,
                        UniversityOffer = model.UniversityOffer,
                        Firm = model.Firm,
                        ApplicantId = model.ApplicantId
                    };

                    _applicationService.Save(application);

                    model.ApplicationId = application.ApplicationId;

                    return RedirectToAction("Index", new { applicantId = model.ApplicantId });
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error", "Unexpected error occurs");
            }

            return View("EditApplication", model);
        }

        /// Delete application for particuler applicant
        /// <param name="applicationId"></param>
        /// <param name="applicantId"></param>
        [HttpPost]
        public ActionResult Delete(int applicationId, int applicantId)
        {
            _applicationService.Delete(applicationId);
            return RedirectToAction("Index", new { applicantId });
        }

        /// Action to accept offer
        /// <param name="applicationId"></param>
        /// <param name="applicantId"></param>
        [HttpPost]
        public ActionResult SetFirm(int applicationId, int applicantId)
        {
            _applicationService.Firm(applicationId);
            return RedirectToAction("Index", new { applicantId });
        }
        
        public JsonResult GetCourses(int universityId)
        {
            var courses = _universityHelper.GetCourses(universityId);
            return Json(courses);
        }

       
    }
}

NAA/Views/ApplicantAdmin/AddApplicant.cshtml
@model NAA.Data.Applicant

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Applicant</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ApplicantName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApplicantName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApplicantName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApplicantAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApplicantAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApplicantAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

NAA/Views/ApplicantAdmin/EditApplicant.cshtml
@model NAA.Data.Applicant

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Applicant</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ApplicantId)

        <div class="form-group">
            @Html.LabelFor(model => model.ApplicantName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApplicantName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApplicantName, "", new
           {
               data_val = false @*@class = "text-danger"*@ })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApplicantAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApplicantAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApplicantAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="form-control text-box single-line display-for-model-text" >
                    @Html.DisplayFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                </span>
                @Html.ValidationMessageFor(model => model.Email, "", new {@class = "text-danger"})
                @Html.HiddenFor(model => model.UserID)
                @Html.HiddenFor(model => model.Email)
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div class="row">
    <div class="col-lg-2">
        @Html.ActionLink("Back", "Applicant","Applicant")
    </div>
    <div class="col-lg-2">
        @Html.ActionLink("Applications List", "Index","Application")
    </div>
</div>

NAA/Views/ApplicantAdmin/Index.cshtml
@model IList<NAA.Data.Applicant>

<table class="table">
    <tr>
        <th>
            Applicant Name
        </th>
        <th>
            Address
        </th>
        <th>
            Phone
        </th>
        <th>
            Email
        </th>
        <th>
            UserID
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ApplicantName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ApplicantAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserID)
            </td>
            <td>
                <a href="@Url.Action("EditApplicant", "ApplicantAdmin", new {id = item.ApplicantId})">Edit</a> 
                |
                <a href="@Url.Action("EditApplicant","ApplicantAdmin", new { id = item.ApplicantId })">Detail</a>
            </td>
        </tr>
    }

</table>